apiVersion: v1
kind: Template
metadata:
  name: kafka-connectors
objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaConnector
  metadata:
    name: ${CONNECTOR_NAME}
    labels:
      strimzi.io/cluster: ${KAFKA_CONNECT_INSTANCE}
  spec:
    class: io.debezium.connector.postgresql.PostgresConnector
    tasksMax: ${MAX_TASKS}
    config:
      database.server.name: ${DB_SERVERNAME}
      database.dbname: ${DB_NAME}
      database.hostname: ${DB_HOSTNAME}
      database.port: ${DB_PORT}
      database.user: ${DB_USER}
      database.password: ${DB_PASSWORD}
      topic.prefix: ${TOPIC_PREFIX}
      table.whitelist: ${TABLE_LIST}
      transforms: outbox
      transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
      transforms.outbox.table.field.payload: ${PAYLOAD_NAME}
      plugin.name: pgoutput
parameters:
- name: DB_SERVERNAME
  required: true
  description: Logical name that identifies and provides a namespace for the particular database server
- name: DB_NAME
  required: true
  description: Name for the database
- name: DB_HOSTNAME
  required: true
  description: URI for the target postgres database
- name: DB_PORT
  value: "5432"
  description: Port on which the target postgres database is listening for connections
- name: DB_USER
  value: databasejoe
  description: Username the connector should use to connect to the target postgres database
- name: DB_PASSWORD
  value: "1"
  description: Password for the above user on the target postgres database
- name: KAFKA_CONNECT_INSTANCE
  value: platform-kafka-connect
  description: Name of the target Kafka Connect instance for Connector
- name: CONNECTOR_NAME
  value: platform-connector
  description: Unique name for this Connector resource
- name: MAX_TASKS
  value: "1"
  description: How many tasks the Kafka Connect instance can create to process this Connector's work
- name: TABLE_LIST
  value: public.management_outbox
  description: The list of tables from which the connector captures change events. 
- name: PAYLOAD_NAME
  value: payload
  description: Specify the field that contains the message payload in the outbox table

